module.exports = {
  ArrayExpression: require('./ArrayExpression'),
  AssignmentExpression: require('./AssignmentExpression'),
  BinaryExpression: require('./BinaryExpression'),
  BlockStatement: require('./BlockStatement'),
  BreakStatement: require('./BreakStatement'),
  CallExpression: require('./CallExpression'),
  ExpressionStatement: require('./ExpressionStatement'),
  ForStatement: require('./ForStatement'),
  FunctionDeclaration: require('./FunctionDeclaration'),
  FunctionExpression: require('./FunctionExpression'),
  Identifier: require('./Identifier'),
  IfStatement: require('./IfStatement'),
  Literal: require('./Literal'),
  MemberExpression: require('./MemberExpression'),
  NewExpression: require('./NewExpression'),
  ObjectExpression: require('./ObjectExpression'),
  Program: require('./Program'),
  ReturnStatement: require('./ReturnStatement'),
  ThisExpression: require('./ThisExpression'),
  VariableDeclaration: require('./VariableDeclaration'),
  VariableDeclarator: require('./VariableDeclarator'),
 }
